#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'RxValidatorExample' do
  pod 'RxValidator', :path => '../../'
  pod 'RxSwift', '>= 4.1.0'
  pod 'RxCocoa', '>= 4.1.0'
  pod 'RxOptional'

  target 'RxValidatorExampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '1.3.1'
    pod 'Nimble', '7.3.0'
  end
end
